// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aelf_sdk.go/aelf_sdk/proto/client.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThresholdCheckType int32

const (
	ThresholdCheckType_BALANCE   ThresholdCheckType = 0
	ThresholdCheckType_ALLOWANCE ThresholdCheckType = 1
)

var ThresholdCheckType_name = map[int32]string{
	0: "BALANCE",
	1: "ALLOWANCE",
}

var ThresholdCheckType_value = map[string]int32{
	"BALANCE":   0,
	"ALLOWANCE": 1,
}

func (x ThresholdCheckType) String() string {
	return proto.EnumName(ThresholdCheckType_name, int32(x))
}

func (ThresholdCheckType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{0}
}

type Address struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value" form:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Hash struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value" form:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{1}
}

func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (m *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(m, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MerklePath struct {
	MerklePathNodes      []*MerklePathNode `protobuf:"bytes,1,rep,name=merkle_path_nodes,json=merklePathNodes,proto3" json:"merkle_path_nodes" form:"merkle_path_nodes"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MerklePath) Reset()         { *m = MerklePath{} }
func (m *MerklePath) String() string { return proto.CompactTextString(m) }
func (*MerklePath) ProtoMessage()    {}
func (*MerklePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{2}
}

func (m *MerklePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerklePath.Unmarshal(m, b)
}
func (m *MerklePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerklePath.Marshal(b, m, deterministic)
}
func (m *MerklePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerklePath.Merge(m, src)
}
func (m *MerklePath) XXX_Size() int {
	return xxx_messageInfo_MerklePath.Size(m)
}
func (m *MerklePath) XXX_DiscardUnknown() {
	xxx_messageInfo_MerklePath.DiscardUnknown(m)
}

var xxx_messageInfo_MerklePath proto.InternalMessageInfo

func (m *MerklePath) GetMerklePathNodes() []*MerklePathNode {
	if m != nil {
		return m.MerklePathNodes
	}
	return nil
}

type MerklePathNode struct {
	Hash                 *Hash    `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash" form:"hash"`
	IsLeftChildNode      bool     `protobuf:"varint,2,opt,name=is_left_child_node,json=isLeftChildNode,proto3" json:"is_left_child_node" form:"is_left_child_node"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerklePathNode) Reset()         { *m = MerklePathNode{} }
func (m *MerklePathNode) String() string { return proto.CompactTextString(m) }
func (*MerklePathNode) ProtoMessage()    {}
func (*MerklePathNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{3}
}

func (m *MerklePathNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerklePathNode.Unmarshal(m, b)
}
func (m *MerklePathNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerklePathNode.Marshal(b, m, deterministic)
}
func (m *MerklePathNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerklePathNode.Merge(m, src)
}
func (m *MerklePathNode) XXX_Size() int {
	return xxx_messageInfo_MerklePathNode.Size(m)
}
func (m *MerklePathNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MerklePathNode.DiscardUnknown(m)
}

var xxx_messageInfo_MerklePathNode proto.InternalMessageInfo

func (m *MerklePathNode) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MerklePathNode) GetIsLeftChildNode() bool {
	if m != nil {
		return m.IsLeftChildNode
	}
	return false
}

type BinaryMerkleTree struct {
	Nodes                []*Hash  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes" form:"nodes"`
	Root                 *Hash    `protobuf:"bytes,2,opt,name=root,proto3" json:"root" form:"root"`
	LeafCount            int32    `protobuf:"varint,3,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count" form:"leaf_count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryMerkleTree) Reset()         { *m = BinaryMerkleTree{} }
func (m *BinaryMerkleTree) String() string { return proto.CompactTextString(m) }
func (*BinaryMerkleTree) ProtoMessage()    {}
func (*BinaryMerkleTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{4}
}

func (m *BinaryMerkleTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryMerkleTree.Unmarshal(m, b)
}
func (m *BinaryMerkleTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryMerkleTree.Marshal(b, m, deterministic)
}
func (m *BinaryMerkleTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryMerkleTree.Merge(m, src)
}
func (m *BinaryMerkleTree) XXX_Size() int {
	return xxx_messageInfo_BinaryMerkleTree.Size(m)
}
func (m *BinaryMerkleTree) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryMerkleTree.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryMerkleTree proto.InternalMessageInfo

func (m *BinaryMerkleTree) GetNodes() []*Hash {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *BinaryMerkleTree) GetRoot() *Hash {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *BinaryMerkleTree) GetLeafCount() int32 {
	if m != nil {
		return m.LeafCount
	}
	return 0
}

type ScopedStatePath struct {
	Address              *Address   `protobuf:"bytes,1,opt,name=address,proto3" json:"address" form:"address"`
	Path                 *StatePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path" form:"path"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScopedStatePath) Reset()         { *m = ScopedStatePath{} }
func (m *ScopedStatePath) String() string { return proto.CompactTextString(m) }
func (*ScopedStatePath) ProtoMessage()    {}
func (*ScopedStatePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{5}
}

func (m *ScopedStatePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopedStatePath.Unmarshal(m, b)
}
func (m *ScopedStatePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopedStatePath.Marshal(b, m, deterministic)
}
func (m *ScopedStatePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedStatePath.Merge(m, src)
}
func (m *ScopedStatePath) XXX_Size() int {
	return xxx_messageInfo_ScopedStatePath.Size(m)
}
func (m *ScopedStatePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedStatePath.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedStatePath proto.InternalMessageInfo

func (m *ScopedStatePath) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ScopedStatePath) GetPath() *StatePath {
	if m != nil {
		return m.Path
	}
	return nil
}

type StatePath struct {
	Parts                []string `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts" form:"parts"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatePath) Reset()         { *m = StatePath{} }
func (m *StatePath) String() string { return proto.CompactTextString(m) }
func (*StatePath) ProtoMessage()    {}
func (*StatePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{6}
}

func (m *StatePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatePath.Unmarshal(m, b)
}
func (m *StatePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatePath.Marshal(b, m, deterministic)
}
func (m *StatePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatePath.Merge(m, src)
}
func (m *StatePath) XXX_Size() int {
	return xxx_messageInfo_StatePath.Size(m)
}
func (m *StatePath) XXX_DiscardUnknown() {
	xxx_messageInfo_StatePath.DiscardUnknown(m)
}

var xxx_messageInfo_StatePath proto.InternalMessageInfo

func (m *StatePath) GetParts() []string {
	if m != nil {
		return m.Parts
	}
	return nil
}

type SmartContractRegistration struct {
	Category             int32    `protobuf:"varint,1,opt,name=category,proto3" json:"category" form:"category"`
	Code                 []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code" form:"code"`
	CodeHash             *Hash    `protobuf:"bytes,3,opt,name=code_hash,json=codeHash,proto3" json:"code_hash" form:"code_hash"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractRegistration) Reset()         { *m = SmartContractRegistration{} }
func (m *SmartContractRegistration) String() string { return proto.CompactTextString(m) }
func (*SmartContractRegistration) ProtoMessage()    {}
func (*SmartContractRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{7}
}

func (m *SmartContractRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractRegistration.Unmarshal(m, b)
}
func (m *SmartContractRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractRegistration.Marshal(b, m, deterministic)
}
func (m *SmartContractRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractRegistration.Merge(m, src)
}
func (m *SmartContractRegistration) XXX_Size() int {
	return xxx_messageInfo_SmartContractRegistration.Size(m)
}
func (m *SmartContractRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractRegistration proto.InternalMessageInfo

func (m *SmartContractRegistration) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *SmartContractRegistration) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SmartContractRegistration) GetCodeHash() *Hash {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

//acs0
type ContractInfo struct {
	SerialNumber         uint64   `protobuf:"varint,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number" form:"serial_number"`
	Category             int32    `protobuf:"varint,3,opt,name=category,proto3" json:"category" form:"category"`
	CodeHash             *Hash    `protobuf:"bytes,4,opt,name=code_hash,json=codeHash,proto3" json:"code_hash" form:"code_hash"`
	IsSystemContract     bool     `protobuf:"varint,5,opt,name=is_system_contract,json=isSystemContract,proto3" json:"is_system_contract" form:"is_system_contract"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractInfo) Reset()         { *m = ContractInfo{} }
func (m *ContractInfo) String() string { return proto.CompactTextString(m) }
func (*ContractInfo) ProtoMessage()    {}
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{8}
}

func (m *ContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractInfo.Unmarshal(m, b)
}
func (m *ContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractInfo.Marshal(b, m, deterministic)
}
func (m *ContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractInfo.Merge(m, src)
}
func (m *ContractInfo) XXX_Size() int {
	return xxx_messageInfo_ContractInfo.Size(m)
}
func (m *ContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContractInfo proto.InternalMessageInfo

func (m *ContractInfo) GetSerialNumber() uint64 {
	if m != nil {
		return m.SerialNumber
	}
	return 0
}

func (m *ContractInfo) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *ContractInfo) GetCodeHash() *Hash {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *ContractInfo) GetIsSystemContract() bool {
	if m != nil {
		return m.IsSystemContract
	}
	return false
}

//acs1
type MethodFees struct {
	MethodName           string       `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name" form:"method_name"`
	Fees                 []*MethodFee `protobuf:"bytes,2,rep,name=fees,proto3" json:"fees" form:"fees"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MethodFees) Reset()         { *m = MethodFees{} }
func (m *MethodFees) String() string { return proto.CompactTextString(m) }
func (*MethodFees) ProtoMessage()    {}
func (*MethodFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{9}
}

func (m *MethodFees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodFees.Unmarshal(m, b)
}
func (m *MethodFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodFees.Marshal(b, m, deterministic)
}
func (m *MethodFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodFees.Merge(m, src)
}
func (m *MethodFees) XXX_Size() int {
	return xxx_messageInfo_MethodFees.Size(m)
}
func (m *MethodFees) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodFees.DiscardUnknown(m)
}

var xxx_messageInfo_MethodFees proto.InternalMessageInfo

func (m *MethodFees) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *MethodFees) GetFees() []*MethodFee {
	if m != nil {
		return m.Fees
	}
	return nil
}

type MethodFee struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol" form:"symbol"`
	BasicFee             int64    `protobuf:"zigzag64,2,opt,name=basic_fee,json=basicFee,proto3" json:"basic_fee" form:"basic_fee"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodFee) Reset()         { *m = MethodFee{} }
func (m *MethodFee) String() string { return proto.CompactTextString(m) }
func (*MethodFee) ProtoMessage()    {}
func (*MethodFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{10}
}

func (m *MethodFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodFee.Unmarshal(m, b)
}
func (m *MethodFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodFee.Marshal(b, m, deterministic)
}
func (m *MethodFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodFee.Merge(m, src)
}
func (m *MethodFee) XXX_Size() int {
	return xxx_messageInfo_MethodFee.Size(m)
}
func (m *MethodFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodFee.DiscardUnknown(m)
}

var xxx_messageInfo_MethodFee proto.InternalMessageInfo

func (m *MethodFee) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MethodFee) GetBasicFee() int64 {
	if m != nil {
		return m.BasicFee
	}
	return 0
}

//acs2
type ResourceInfo struct {
	Paths                []*ScopedStatePath `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths" form:"paths"`
	NonParallelizable    bool               `protobuf:"varint,2,opt,name=non_parallelizable,json=nonParallelizable,proto3" json:"non_parallelizable" form:"non_parallelizable"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResourceInfo) Reset()         { *m = ResourceInfo{} }
func (m *ResourceInfo) String() string { return proto.CompactTextString(m) }
func (*ResourceInfo) ProtoMessage()    {}
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{11}
}

func (m *ResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceInfo.Unmarshal(m, b)
}
func (m *ResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceInfo.Marshal(b, m, deterministic)
}
func (m *ResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceInfo.Merge(m, src)
}
func (m *ResourceInfo) XXX_Size() int {
	return xxx_messageInfo_ResourceInfo.Size(m)
}
func (m *ResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceInfo proto.InternalMessageInfo

func (m *ResourceInfo) GetPaths() []*ScopedStatePath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *ResourceInfo) GetNonParallelizable() bool {
	if m != nil {
		return m.NonParallelizable
	}
	return false
}

// acs3
type ProposalOutput struct {
	ProposalId           *Hash                `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id" form:"proposal_id"`
	ContractMethodName   string               `protobuf:"bytes,2,opt,name=contract_method_name,json=contractMethodName,proto3" json:"contract_method_name" form:"contract_method_name"`
	ToAddress            *Address             `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address" form:"to_address"`
	Params               []byte               `protobuf:"bytes,4,opt,name=params,proto3" json:"params" form:"params"`
	ExpiredTime          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time" form:"expired_time"`
	OrganizationAddress  *Address             `protobuf:"bytes,6,opt,name=organization_address,json=organizationAddress,proto3" json:"organization_address" form:"organization_address"`
	Proposer             *Address             `protobuf:"bytes,7,opt,name=proposer,proto3" json:"proposer" form:"proposer"`
	ToBeReleased         bool                 `protobuf:"varint,8,opt,name=to_be_released,json=toBeReleased,proto3" json:"to_be_released" form:"to_be_released"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProposalOutput) Reset()         { *m = ProposalOutput{} }
func (m *ProposalOutput) String() string { return proto.CompactTextString(m) }
func (*ProposalOutput) ProtoMessage()    {}
func (*ProposalOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{12}
}

func (m *ProposalOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalOutput.Unmarshal(m, b)
}
func (m *ProposalOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalOutput.Marshal(b, m, deterministic)
}
func (m *ProposalOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalOutput.Merge(m, src)
}
func (m *ProposalOutput) XXX_Size() int {
	return xxx_messageInfo_ProposalOutput.Size(m)
}
func (m *ProposalOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalOutput proto.InternalMessageInfo

func (m *ProposalOutput) GetProposalId() *Hash {
	if m != nil {
		return m.ProposalId
	}
	return nil
}

func (m *ProposalOutput) GetContractMethodName() string {
	if m != nil {
		return m.ContractMethodName
	}
	return ""
}

func (m *ProposalOutput) GetToAddress() *Address {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *ProposalOutput) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ProposalOutput) GetExpiredTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiredTime
	}
	return nil
}

func (m *ProposalOutput) GetOrganizationAddress() *Address {
	if m != nil {
		return m.OrganizationAddress
	}
	return nil
}

func (m *ProposalOutput) GetProposer() *Address {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *ProposalOutput) GetToBeReleased() bool {
	if m != nil {
		return m.ToBeReleased
	}
	return false
}

type ValidationResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success" form:"success"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message" form:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResult) Reset()         { *m = ValidationResult{} }
func (m *ValidationResult) String() string { return proto.CompactTextString(m) }
func (*ValidationResult) ProtoMessage()    {}
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{13}
}

func (m *ValidationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResult.Unmarshal(m, b)
}
func (m *ValidationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResult.Marshal(b, m, deterministic)
}
func (m *ValidationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResult.Merge(m, src)
}
func (m *ValidationResult) XXX_Size() int {
	return xxx_messageInfo_ValidationResult.Size(m)
}
func (m *ValidationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResult proto.InternalMessageInfo

func (m *ValidationResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ValidationResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//acs5
type MethodCallingThreshold struct {
	SymbolToAmount       map[string]int64   `protobuf:"bytes,1,rep,name=symbol_to_amount,json=symbolToAmount,proto3" json:"symbol_to_amount" form:"symbol_to_amount" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	ThresholdCheckType   ThresholdCheckType `protobuf:"varint,2,opt,name=threshold_check_type,json=thresholdCheckType,proto3,enum=client.ThresholdCheckType" json:"threshold_check_type" form:"threshold_check_type"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MethodCallingThreshold) Reset()         { *m = MethodCallingThreshold{} }
func (m *MethodCallingThreshold) String() string { return proto.CompactTextString(m) }
func (*MethodCallingThreshold) ProtoMessage()    {}
func (*MethodCallingThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{14}
}

func (m *MethodCallingThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodCallingThreshold.Unmarshal(m, b)
}
func (m *MethodCallingThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodCallingThreshold.Marshal(b, m, deterministic)
}
func (m *MethodCallingThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodCallingThreshold.Merge(m, src)
}
func (m *MethodCallingThreshold) XXX_Size() int {
	return xxx_messageInfo_MethodCallingThreshold.Size(m)
}
func (m *MethodCallingThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodCallingThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_MethodCallingThreshold proto.InternalMessageInfo

func (m *MethodCallingThreshold) GetSymbolToAmount() map[string]int64 {
	if m != nil {
		return m.SymbolToAmount
	}
	return nil
}

func (m *MethodCallingThreshold) GetThresholdCheckType() ThresholdCheckType {
	if m != nil {
		return m.ThresholdCheckType
	}
	return ThresholdCheckType_BALANCE
}

//acs7
type SideChainIdAndHeightDict struct {
	IdHeightDict         map[int32]int64 `protobuf:"bytes,1,rep,name=id_height_dict,json=idHeightDict,proto3" json:"id_height_dict" form:"id_height_dict" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SideChainIdAndHeightDict) Reset()         { *m = SideChainIdAndHeightDict{} }
func (m *SideChainIdAndHeightDict) String() string { return proto.CompactTextString(m) }
func (*SideChainIdAndHeightDict) ProtoMessage()    {}
func (*SideChainIdAndHeightDict) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{15}
}

func (m *SideChainIdAndHeightDict) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideChainIdAndHeightDict.Unmarshal(m, b)
}
func (m *SideChainIdAndHeightDict) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideChainIdAndHeightDict.Marshal(b, m, deterministic)
}
func (m *SideChainIdAndHeightDict) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideChainIdAndHeightDict.Merge(m, src)
}
func (m *SideChainIdAndHeightDict) XXX_Size() int {
	return xxx_messageInfo_SideChainIdAndHeightDict.Size(m)
}
func (m *SideChainIdAndHeightDict) XXX_DiscardUnknown() {
	xxx_messageInfo_SideChainIdAndHeightDict.DiscardUnknown(m)
}

var xxx_messageInfo_SideChainIdAndHeightDict proto.InternalMessageInfo

func (m *SideChainIdAndHeightDict) GetIdHeightDict() map[int32]int64 {
	if m != nil {
		return m.IdHeightDict
	}
	return nil
}

type SideChainIndexingInformationList struct {
	IndexingInformationList []*SideChainIndexingInformation `protobuf:"bytes,1,rep,name=indexing_information_list,json=indexingInformationList,proto3" json:"indexing_information_list" form:"indexing_information_list"`
	XXX_NoUnkeyedLiteral    struct{}                        `json:"-"`
	XXX_unrecognized        []byte                          `json:"-"`
	XXX_sizecache           int32                           `json:"-"`
}

func (m *SideChainIndexingInformationList) Reset()         { *m = SideChainIndexingInformationList{} }
func (m *SideChainIndexingInformationList) String() string { return proto.CompactTextString(m) }
func (*SideChainIndexingInformationList) ProtoMessage()    {}
func (*SideChainIndexingInformationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{16}
}

func (m *SideChainIndexingInformationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideChainIndexingInformationList.Unmarshal(m, b)
}
func (m *SideChainIndexingInformationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideChainIndexingInformationList.Marshal(b, m, deterministic)
}
func (m *SideChainIndexingInformationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideChainIndexingInformationList.Merge(m, src)
}
func (m *SideChainIndexingInformationList) XXX_Size() int {
	return xxx_messageInfo_SideChainIndexingInformationList.Size(m)
}
func (m *SideChainIndexingInformationList) XXX_DiscardUnknown() {
	xxx_messageInfo_SideChainIndexingInformationList.DiscardUnknown(m)
}

var xxx_messageInfo_SideChainIndexingInformationList proto.InternalMessageInfo

func (m *SideChainIndexingInformationList) GetIndexingInformationList() []*SideChainIndexingInformation {
	if m != nil {
		return m.IndexingInformationList
	}
	return nil
}

type SideChainIndexingInformation struct {
	ChainId              int32    `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id" form:"chain_id"`
	IndexedHeight        int64    `protobuf:"varint,2,opt,name=indexed_height,json=indexedHeight,proto3" json:"indexed_height" form:"indexed_height"`
	ToBeIndexedCount     int64    `protobuf:"varint,3,opt,name=to_be_indexed_count,json=toBeIndexedCount,proto3" json:"to_be_indexed_count" form:"to_be_indexed_count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SideChainIndexingInformation) Reset()         { *m = SideChainIndexingInformation{} }
func (m *SideChainIndexingInformation) String() string { return proto.CompactTextString(m) }
func (*SideChainIndexingInformation) ProtoMessage()    {}
func (*SideChainIndexingInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{17}
}

func (m *SideChainIndexingInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideChainIndexingInformation.Unmarshal(m, b)
}
func (m *SideChainIndexingInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideChainIndexingInformation.Marshal(b, m, deterministic)
}
func (m *SideChainIndexingInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideChainIndexingInformation.Merge(m, src)
}
func (m *SideChainIndexingInformation) XXX_Size() int {
	return xxx_messageInfo_SideChainIndexingInformation.Size(m)
}
func (m *SideChainIndexingInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_SideChainIndexingInformation.DiscardUnknown(m)
}

var xxx_messageInfo_SideChainIndexingInformation proto.InternalMessageInfo

func (m *SideChainIndexingInformation) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *SideChainIndexingInformation) GetIndexedHeight() int64 {
	if m != nil {
		return m.IndexedHeight
	}
	return 0
}

func (m *SideChainIndexingInformation) GetToBeIndexedCount() int64 {
	if m != nil {
		return m.ToBeIndexedCount
	}
	return 0
}

type CrossChainBlockData struct {
	SideChainBlockData   []*SideChainBlockData   `protobuf:"bytes,1,rep,name=side_chain_block_data,json=sideChainBlockData,proto3" json:"side_chain_block_data" form:"side_chain_block_data"`
	ParentChainBlockData []*ParentChainBlockData `protobuf:"bytes,2,rep,name=parent_chain_block_data,json=parentChainBlockData,proto3" json:"parent_chain_block_data" form:"parent_chain_block_data"`
	PreviousBlockHeight  int64                   `protobuf:"varint,3,opt,name=previous_block_height,json=previousBlockHeight,proto3" json:"previous_block_height" form:"previous_block_height"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CrossChainBlockData) Reset()         { *m = CrossChainBlockData{} }
func (m *CrossChainBlockData) String() string { return proto.CompactTextString(m) }
func (*CrossChainBlockData) ProtoMessage()    {}
func (*CrossChainBlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{18}
}

func (m *CrossChainBlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossChainBlockData.Unmarshal(m, b)
}
func (m *CrossChainBlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossChainBlockData.Marshal(b, m, deterministic)
}
func (m *CrossChainBlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainBlockData.Merge(m, src)
}
func (m *CrossChainBlockData) XXX_Size() int {
	return xxx_messageInfo_CrossChainBlockData.Size(m)
}
func (m *CrossChainBlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainBlockData.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainBlockData proto.InternalMessageInfo

func (m *CrossChainBlockData) GetSideChainBlockData() []*SideChainBlockData {
	if m != nil {
		return m.SideChainBlockData
	}
	return nil
}

func (m *CrossChainBlockData) GetParentChainBlockData() []*ParentChainBlockData {
	if m != nil {
		return m.ParentChainBlockData
	}
	return nil
}

func (m *CrossChainBlockData) GetPreviousBlockHeight() int64 {
	if m != nil {
		return m.PreviousBlockHeight
	}
	return 0
}

type SideChainBlockData struct {
	Height                          int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height" form:"height"`
	BlockHeaderHash                 *Hash    `protobuf:"bytes,2,opt,name=block_header_hash,json=blockHeaderHash,proto3" json:"block_header_hash" form:"block_header_hash"`
	TransactionStatusMerkleTreeRoot *Hash    `protobuf:"bytes,3,opt,name=transaction_status_merkle_tree_root,json=transactionStatusMerkleTreeRoot,proto3" json:"transaction_status_merkle_tree_root" form:"transaction_status_merkle_tree_root"`
	ChainId                         int32    `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id" form:"chain_id"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *SideChainBlockData) Reset()         { *m = SideChainBlockData{} }
func (m *SideChainBlockData) String() string { return proto.CompactTextString(m) }
func (*SideChainBlockData) ProtoMessage()    {}
func (*SideChainBlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{19}
}

func (m *SideChainBlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideChainBlockData.Unmarshal(m, b)
}
func (m *SideChainBlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideChainBlockData.Marshal(b, m, deterministic)
}
func (m *SideChainBlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideChainBlockData.Merge(m, src)
}
func (m *SideChainBlockData) XXX_Size() int {
	return xxx_messageInfo_SideChainBlockData.Size(m)
}
func (m *SideChainBlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_SideChainBlockData.DiscardUnknown(m)
}

var xxx_messageInfo_SideChainBlockData proto.InternalMessageInfo

func (m *SideChainBlockData) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SideChainBlockData) GetBlockHeaderHash() *Hash {
	if m != nil {
		return m.BlockHeaderHash
	}
	return nil
}

func (m *SideChainBlockData) GetTransactionStatusMerkleTreeRoot() *Hash {
	if m != nil {
		return m.TransactionStatusMerkleTreeRoot
	}
	return nil
}

func (m *SideChainBlockData) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

type ParentChainBlockData struct {
	Height                          int64                `protobuf:"varint,1,opt,name=height,proto3" json:"height" form:"height"`
	CrossChainExtraData             *CrossChainExtraData `protobuf:"bytes,2,opt,name=cross_chain_extra_data,json=crossChainExtraData,proto3" json:"cross_chain_extra_data" form:"cross_chain_extra_data"`
	ChainId                         int32                `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id" form:"chain_id"`
	TransactionStatusMerkleTreeRoot *Hash                `protobuf:"bytes,4,opt,name=transaction_status_merkle_tree_root,json=transactionStatusMerkleTreeRoot,proto3" json:"transaction_status_merkle_tree_root" form:"transaction_status_merkle_tree_root"`
	// Indexed block height from side chain and merkle path for this side chain block
	IndexedMerklePath    map[int64]*MerklePath `protobuf:"bytes,5,rep,name=indexed_merkle_path,json=indexedMerklePath,proto3" json:"indexed_merkle_path" form:"indexed_merkle_path" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ExtraData            map[string][]byte     `protobuf:"bytes,6,rep,name=extra_data,json=extraData,proto3" json:"extra_data" form:"extra_data" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ParentChainBlockData) Reset()         { *m = ParentChainBlockData{} }
func (m *ParentChainBlockData) String() string { return proto.CompactTextString(m) }
func (*ParentChainBlockData) ProtoMessage()    {}
func (*ParentChainBlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{20}
}

func (m *ParentChainBlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentChainBlockData.Unmarshal(m, b)
}
func (m *ParentChainBlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentChainBlockData.Marshal(b, m, deterministic)
}
func (m *ParentChainBlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentChainBlockData.Merge(m, src)
}
func (m *ParentChainBlockData) XXX_Size() int {
	return xxx_messageInfo_ParentChainBlockData.Size(m)
}
func (m *ParentChainBlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentChainBlockData.DiscardUnknown(m)
}

var xxx_messageInfo_ParentChainBlockData proto.InternalMessageInfo

func (m *ParentChainBlockData) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParentChainBlockData) GetCrossChainExtraData() *CrossChainExtraData {
	if m != nil {
		return m.CrossChainExtraData
	}
	return nil
}

func (m *ParentChainBlockData) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ParentChainBlockData) GetTransactionStatusMerkleTreeRoot() *Hash {
	if m != nil {
		return m.TransactionStatusMerkleTreeRoot
	}
	return nil
}

func (m *ParentChainBlockData) GetIndexedMerklePath() map[int64]*MerklePath {
	if m != nil {
		return m.IndexedMerklePath
	}
	return nil
}

func (m *ParentChainBlockData) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type CrossChainExtraData struct {
	// Merkle tree root of side chain block transaction status root
	TransactionStatusMerkleTreeRoot *Hash    `protobuf:"bytes,1,opt,name=transaction_status_merkle_tree_root,json=transactionStatusMerkleTreeRoot,proto3" json:"transaction_status_merkle_tree_root" form:"transaction_status_merkle_tree_root"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *CrossChainExtraData) Reset()         { *m = CrossChainExtraData{} }
func (m *CrossChainExtraData) String() string { return proto.CompactTextString(m) }
func (*CrossChainExtraData) ProtoMessage()    {}
func (*CrossChainExtraData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{21}
}

func (m *CrossChainExtraData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossChainExtraData.Unmarshal(m, b)
}
func (m *CrossChainExtraData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossChainExtraData.Marshal(b, m, deterministic)
}
func (m *CrossChainExtraData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainExtraData.Merge(m, src)
}
func (m *CrossChainExtraData) XXX_Size() int {
	return xxx_messageInfo_CrossChainExtraData.Size(m)
}
func (m *CrossChainExtraData) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainExtraData.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainExtraData proto.InternalMessageInfo

func (m *CrossChainExtraData) GetTransactionStatusMerkleTreeRoot() *Hash {
	if m != nil {
		return m.TransactionStatusMerkleTreeRoot
	}
	return nil
}

type IndexedSideChainBlockData struct {
	SideChainBlockData   []*SideChainBlockData `protobuf:"bytes,1,rep,name=side_chain_block_data,json=sideChainBlockData,proto3" json:"side_chain_block_data" form:"side_chain_block_data"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IndexedSideChainBlockData) Reset()         { *m = IndexedSideChainBlockData{} }
func (m *IndexedSideChainBlockData) String() string { return proto.CompactTextString(m) }
func (*IndexedSideChainBlockData) ProtoMessage()    {}
func (*IndexedSideChainBlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{22}
}

func (m *IndexedSideChainBlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexedSideChainBlockData.Unmarshal(m, b)
}
func (m *IndexedSideChainBlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexedSideChainBlockData.Marshal(b, m, deterministic)
}
func (m *IndexedSideChainBlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexedSideChainBlockData.Merge(m, src)
}
func (m *IndexedSideChainBlockData) XXX_Size() int {
	return xxx_messageInfo_IndexedSideChainBlockData.Size(m)
}
func (m *IndexedSideChainBlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexedSideChainBlockData.DiscardUnknown(m)
}

var xxx_messageInfo_IndexedSideChainBlockData proto.InternalMessageInfo

func (m *IndexedSideChainBlockData) GetSideChainBlockData() []*SideChainBlockData {
	if m != nil {
		return m.SideChainBlockData
	}
	return nil
}

type CrossChainMerkleProofContext struct {
	BoundParentChainHeight    int64       `protobuf:"varint,1,opt,name=bound_parent_chain_height,json=boundParentChainHeight,proto3" json:"bound_parent_chain_height" form:"bound_parent_chain_height"`
	MerklePathFromParentChain *MerklePath `protobuf:"bytes,2,opt,name=merkle_path_from_parent_chain,json=merklePathFromParentChain,proto3" json:"merkle_path_from_parent_chain" form:"merkle_path_from_parent_chain"`
	XXX_NoUnkeyedLiteral      struct{}    `json:"-"`
	XXX_unrecognized          []byte      `json:"-"`
	XXX_sizecache             int32       `json:"-"`
}

func (m *CrossChainMerkleProofContext) Reset()         { *m = CrossChainMerkleProofContext{} }
func (m *CrossChainMerkleProofContext) String() string { return proto.CompactTextString(m) }
func (*CrossChainMerkleProofContext) ProtoMessage()    {}
func (*CrossChainMerkleProofContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{23}
}

func (m *CrossChainMerkleProofContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossChainMerkleProofContext.Unmarshal(m, b)
}
func (m *CrossChainMerkleProofContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossChainMerkleProofContext.Marshal(b, m, deterministic)
}
func (m *CrossChainMerkleProofContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainMerkleProofContext.Merge(m, src)
}
func (m *CrossChainMerkleProofContext) XXX_Size() int {
	return xxx_messageInfo_CrossChainMerkleProofContext.Size(m)
}
func (m *CrossChainMerkleProofContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainMerkleProofContext.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainMerkleProofContext proto.InternalMessageInfo

func (m *CrossChainMerkleProofContext) GetBoundParentChainHeight() int64 {
	if m != nil {
		return m.BoundParentChainHeight
	}
	return 0
}

func (m *CrossChainMerkleProofContext) GetMerklePathFromParentChain() *MerklePath {
	if m != nil {
		return m.MerklePathFromParentChain
	}
	return nil
}

type ChainInitializationData struct {
	ChainId                        int32                `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id" form:"chain_id"`
	Creator                        *Address             `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator" form:"creator"`
	CreationTimestamp              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp" form:"creation_timestamp"`
	ExtraInformation               [][]byte             `protobuf:"bytes,4,rep,name=extra_information,json=extraInformation,proto3" json:"extra_information" form:"extra_information"`
	CreationHeightOnParentChain    int64                `protobuf:"varint,5,opt,name=creation_height_on_parent_chain,json=creationHeightOnParentChain,proto3" json:"creation_height_on_parent_chain" form:"creation_height_on_parent_chain"`
	ChainCreatorPrivilegePreserved bool                 `protobuf:"varint,6,opt,name=chain_creator_privilege_preserved,json=chainCreatorPrivilegePreserved,proto3" json:"chain_creator_privilege_preserved" form:"chain_creator_privilege_preserved"`
	SideChainTokenSymbol           string               `protobuf:"bytes,7,opt,name=side_chain_token_symbol,json=sideChainTokenSymbol,proto3" json:"side_chain_token_symbol" form:"side_chain_token_symbol"`
	XXX_NoUnkeyedLiteral           struct{}             `json:"-"`
	XXX_unrecognized               []byte               `json:"-"`
	XXX_sizecache                  int32                `json:"-"`
}

func (m *ChainInitializationData) Reset()         { *m = ChainInitializationData{} }
func (m *ChainInitializationData) String() string { return proto.CompactTextString(m) }
func (*ChainInitializationData) ProtoMessage()    {}
func (*ChainInitializationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{24}
}

func (m *ChainInitializationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInitializationData.Unmarshal(m, b)
}
func (m *ChainInitializationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInitializationData.Marshal(b, m, deterministic)
}
func (m *ChainInitializationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInitializationData.Merge(m, src)
}
func (m *ChainInitializationData) XXX_Size() int {
	return xxx_messageInfo_ChainInitializationData.Size(m)
}
func (m *ChainInitializationData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInitializationData.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInitializationData proto.InternalMessageInfo

func (m *ChainInitializationData) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ChainInitializationData) GetCreator() *Address {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *ChainInitializationData) GetCreationTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTimestamp
	}
	return nil
}

func (m *ChainInitializationData) GetExtraInformation() [][]byte {
	if m != nil {
		return m.ExtraInformation
	}
	return nil
}

func (m *ChainInitializationData) GetCreationHeightOnParentChain() int64 {
	if m != nil {
		return m.CreationHeightOnParentChain
	}
	return 0
}

func (m *ChainInitializationData) GetChainCreatorPrivilegePreserved() bool {
	if m != nil {
		return m.ChainCreatorPrivilegePreserved
	}
	return false
}

func (m *ChainInitializationData) GetSideChainTokenSymbol() string {
	if m != nil {
		return m.SideChainTokenSymbol
	}
	return ""
}

type Transaction struct {
	From                 *Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from" form:"from"`
	To                   *Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to" form:"to"`
	RefBlockNumber       int64    `protobuf:"varint,3,opt,name=refBlockNumber,proto3" json:"refBlockNumber" form:"refBlockNumber"`
	RefBlockPrefix       []byte   `protobuf:"bytes,4,opt,name=refBlockPrefix,proto3" json:"refBlockPrefix" form:"refBlockPrefix"`
	MethodName           string   `protobuf:"bytes,5,opt,name=methodName,proto3" json:"methodName" form:"methodName"`
	Params               []byte   `protobuf:"bytes,6,opt,name=params,proto3" json:"params" form:"params"`
	Signature            []byte   `protobuf:"bytes,10000,opt,name=signature,proto3" json:"signature" form:"signature"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d88724c620d246, []int{25}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetRefBlockNumber() int64 {
	if m != nil {
		return m.RefBlockNumber
	}
	return 0
}

func (m *Transaction) GetRefBlockPrefix() []byte {
	if m != nil {
		return m.RefBlockPrefix
	}
	return nil
}

func (m *Transaction) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *Transaction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("client.ThresholdCheckType", ThresholdCheckType_name, ThresholdCheckType_value)
	proto.RegisterType((*Address)(nil), "client.Address")
	proto.RegisterType((*Hash)(nil), "client.Hash")
	proto.RegisterType((*MerklePath)(nil), "client.MerklePath")
	proto.RegisterType((*MerklePathNode)(nil), "client.MerklePathNode")
	proto.RegisterType((*BinaryMerkleTree)(nil), "client.BinaryMerkleTree")
	proto.RegisterType((*ScopedStatePath)(nil), "client.ScopedStatePath")
	proto.RegisterType((*StatePath)(nil), "client.StatePath")
	proto.RegisterType((*SmartContractRegistration)(nil), "client.SmartContractRegistration")
	proto.RegisterType((*ContractInfo)(nil), "client.ContractInfo")
	proto.RegisterType((*MethodFees)(nil), "client.MethodFees")
	proto.RegisterType((*MethodFee)(nil), "client.MethodFee")
	proto.RegisterType((*ResourceInfo)(nil), "client.ResourceInfo")
	proto.RegisterType((*ProposalOutput)(nil), "client.ProposalOutput")
	proto.RegisterType((*ValidationResult)(nil), "client.ValidationResult")
	proto.RegisterType((*MethodCallingThreshold)(nil), "client.MethodCallingThreshold")
	proto.RegisterMapType((map[string]int64)(nil), "client.MethodCallingThreshold.SymbolToAmountEntry")
	proto.RegisterType((*SideChainIdAndHeightDict)(nil), "client.SideChainIdAndHeightDict")
	proto.RegisterMapType((map[int32]int64)(nil), "client.SideChainIdAndHeightDict.IdHeightDictEntry")
	proto.RegisterType((*SideChainIndexingInformationList)(nil), "client.SideChainIndexingInformationList")
	proto.RegisterType((*SideChainIndexingInformation)(nil), "client.SideChainIndexingInformation")
	proto.RegisterType((*CrossChainBlockData)(nil), "client.CrossChainBlockData")
	proto.RegisterType((*SideChainBlockData)(nil), "client.SideChainBlockData")
	proto.RegisterType((*ParentChainBlockData)(nil), "client.ParentChainBlockData")
	proto.RegisterMapType((map[string][]byte)(nil), "client.ParentChainBlockData.ExtraDataEntry")
	proto.RegisterMapType((map[int64]*MerklePath)(nil), "client.ParentChainBlockData.IndexedMerklePathEntry")
	proto.RegisterType((*CrossChainExtraData)(nil), "client.CrossChainExtraData")
	proto.RegisterType((*IndexedSideChainBlockData)(nil), "client.IndexedSideChainBlockData")
	proto.RegisterType((*CrossChainMerkleProofContext)(nil), "client.CrossChainMerkleProofContext")
	proto.RegisterType((*ChainInitializationData)(nil), "client.ChainInitializationData")
	proto.RegisterType((*Transaction)(nil), "client.Transaction")
}

func init() {
	proto.RegisterFile("aelf_sdk.go/aelf_sdk/proto/client.proto", fileDescriptor_f7d88724c620d246)
}

var fileDescriptor_f7d88724c620d246 = []byte{
	// 1759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0x23, 0x49,
	0x11, 0xc7, 0xb1, 0x9d, 0xc4, 0x65, 0xaf, 0x13, 0x77, 0x7c, 0x89, 0xe3, 0xdd, 0xbd, 0xe4, 0x66,
	0xef, 0x20, 0xcb, 0xb2, 0xde, 0x53, 0x4e, 0x48, 0x07, 0x02, 0x41, 0xe2, 0xdd, 0xd5, 0x05, 0x65,
	0xb3, 0xd6, 0xc4, 0x82, 0x13, 0x42, 0x1a, 0xda, 0x33, 0x6d, 0xbb, 0xc9, 0x78, 0x7a, 0xe8, 0x6e,
	0x87, 0xe4, 0x9e, 0x91, 0x78, 0x3c, 0xbe, 0x01, 0xaf, 0x88, 0x17, 0x9e, 0x78, 0xe7, 0x8b, 0xf0,
	0x11, 0xf8, 0x02, 0x3c, 0xa1, 0xfe, 0xe7, 0x99, 0x89, 0x9d, 0x70, 0x3a, 0xf1, 0x34, 0x53, 0x7f,
	0xba, 0xaa, 0xfa, 0x57, 0xd5, 0xd5, 0xd5, 0xf0, 0x3d, 0x4c, 0xe2, 0x71, 0x20, 0xa2, 0xab, 0xde,
	0x84, 0xbd, 0x72, 0xff, 0xaf, 0x52, 0xce, 0x24, 0x7b, 0x15, 0xc6, 0x94, 0x24, 0xb2, 0xa7, 0x09,
	0xb4, 0x6e, 0xa8, 0xee, 0xc1, 0x84, 0xb1, 0x49, 0x4c, 0x8c, 0xca, 0x68, 0x3e, 0x7e, 0x25, 0xe9,
	0x8c, 0x08, 0x89, 0x67, 0xa9, 0x51, 0xf4, 0x0e, 0x60, 0xe3, 0x24, 0x8a, 0x38, 0x11, 0x02, 0xb5,
	0xa1, 0x7a, 0x8d, 0xe3, 0x39, 0xe9, 0x94, 0x0e, 0x4b, 0x47, 0x0d, 0xdf, 0x10, 0xde, 0x13, 0xa8,
	0x7c, 0x81, 0xc5, 0xf4, 0x1e, 0xe9, 0x00, 0xe0, 0x1d, 0xe1, 0x57, 0x31, 0x19, 0x60, 0x39, 0x45,
	0xa7, 0xd0, 0x9a, 0x69, 0x2a, 0x48, 0xb1, 0x9c, 0x06, 0x09, 0x8b, 0x88, 0xe8, 0x94, 0x0e, 0xcb,
	0x47, 0xf5, 0xe3, 0xdd, 0x9e, 0x8d, 0x2f, 0x53, 0xbf, 0x60, 0x11, 0xf1, 0xb7, 0x66, 0x05, 0x5a,
	0x78, 0x01, 0x34, 0x8b, 0x2a, 0xe8, 0x10, 0x2a, 0x53, 0x2c, 0xa6, 0xda, 0x71, 0xfd, 0xb8, 0xe1,
	0x0c, 0xa9, 0xa8, 0x7c, 0x2d, 0x41, 0x2f, 0x00, 0x51, 0x11, 0xc4, 0x64, 0x2c, 0x83, 0x70, 0x4a,
	0xe3, 0x48, 0x7b, 0xee, 0xac, 0x1d, 0x96, 0x8e, 0x36, 0xfd, 0x2d, 0x2a, 0xce, 0xc9, 0x58, 0xf6,
	0x15, 0x5f, 0x99, 0xf3, 0xfe, 0x00, 0xdb, 0xa7, 0x34, 0xc1, 0xfc, 0xd6, 0xb8, 0x19, 0x72, 0x42,
	0x90, 0x07, 0xd5, 0x7c, 0xb0, 0x45, 0x1f, 0x46, 0xa4, 0xc2, 0xe0, 0x8c, 0x49, 0x6d, 0x76, 0x29,
	0x0c, 0x25, 0x41, 0x4f, 0x01, 0x62, 0x82, 0xc7, 0x41, 0xc8, 0xe6, 0x89, 0xec, 0x94, 0x0f, 0x4b,
	0x47, 0x55, 0xbf, 0xa6, 0x38, 0x7d, 0xc5, 0xf0, 0x42, 0xd8, 0xba, 0x0c, 0x59, 0x4a, 0xa2, 0x4b,
	0x89, 0xa5, 0x01, 0xec, 0x39, 0x6c, 0x60, 0x83, 0xbe, 0xdd, 0xdd, 0x96, 0x33, 0x6b, 0x93, 0xe2,
	0x3b, 0x39, 0xfa, 0x04, 0x2a, 0x0a, 0x54, 0xeb, 0xbe, 0xe5, 0xf4, 0x16, 0xb6, 0x7c, 0x2d, 0xf6,
	0x3e, 0x82, 0x5a, 0x66, 0xbe, 0x0d, 0xd5, 0x14, 0x73, 0x69, 0xb6, 0x55, 0xf3, 0x0d, 0xe1, 0x5d,
	0xc3, 0xfe, 0xe5, 0x0c, 0x73, 0xd9, 0x67, 0x89, 0xe4, 0x38, 0x94, 0x3e, 0x99, 0x50, 0x21, 0x39,
	0x96, 0x94, 0x25, 0xa8, 0x0b, 0x9b, 0x21, 0x96, 0x64, 0xc2, 0xf8, 0xad, 0x0e, 0xa9, 0xea, 0x2f,
	0x68, 0x84, 0xa0, 0x12, 0x3a, 0x60, 0x1b, 0xbe, 0xfe, 0x47, 0xcf, 0xa1, 0xa6, 0xbe, 0x81, 0xce,
	0x50, 0x79, 0x05, 0x34, 0x9b, 0x4a, 0xac, 0xfe, 0xbc, 0xbf, 0x96, 0xa0, 0xe1, 0x7c, 0x9e, 0x25,
	0x63, 0x86, 0x9e, 0xc1, 0x23, 0x41, 0x38, 0xc5, 0x71, 0x90, 0xcc, 0x67, 0x23, 0xc2, 0xb5, 0xc3,
	0x8a, 0xdf, 0x30, 0xcc, 0x0b, 0xcd, 0x2b, 0x04, 0x54, 0xbe, 0x13, 0x50, 0xc1, 0x79, 0xe5, 0x21,
	0xe7, 0xe8, 0x07, 0xba, 0x44, 0xc4, 0xad, 0x90, 0x64, 0x16, 0x84, 0x36, 0x8a, 0x4e, 0x55, 0x97,
	0xc8, 0x36, 0x15, 0x97, 0x5a, 0xe0, 0xa2, 0xf3, 0x86, 0xaa, 0xac, 0xe5, 0x94, 0x45, 0x6f, 0x09,
	0x11, 0xe8, 0x00, 0xea, 0x33, 0x4d, 0x05, 0x09, 0x9e, 0x99, 0x03, 0x50, 0xf3, 0xc1, 0xb0, 0x2e,
	0xf0, 0x8c, 0xa8, 0xdc, 0x8c, 0x09, 0x11, 0x9d, 0x35, 0x5d, 0x3d, 0xad, 0xac, 0xd4, 0xad, 0x09,
	0x5f, 0x8b, 0xbd, 0x9f, 0x43, 0x6d, 0xc1, 0x42, 0xbb, 0xb0, 0x2e, 0x6e, 0x67, 0x23, 0x16, 0x5b,
	0x7b, 0x96, 0x42, 0x8f, 0xa1, 0x36, 0xc2, 0x82, 0x86, 0xc1, 0x98, 0x18, 0xa4, 0x91, 0xbf, 0xa9,
	0x19, 0x6f, 0x09, 0xf1, 0x62, 0x68, 0xf8, 0x44, 0xb0, 0x39, 0x0f, 0x89, 0x46, 0xf0, 0xa5, 0x4a,
	0xb0, 0x9c, 0xba, 0xba, 0xdd, 0x5b, 0x54, 0x45, 0xb1, 0xce, 0x7c, 0xa3, 0x85, 0x5e, 0x02, 0x4a,
	0x58, 0x12, 0xa4, 0x98, 0xe3, 0x38, 0x26, 0x31, 0xfd, 0x0a, 0x8f, 0x62, 0x77, 0x4e, 0x5a, 0x09,
	0x4b, 0x06, 0x05, 0x81, 0xf7, 0x75, 0x19, 0x9a, 0x03, 0xce, 0x52, 0x26, 0x70, 0xfc, 0x7e, 0x2e,
	0xd3, 0xb9, 0x44, 0x2f, 0xa1, 0x9e, 0x5a, 0x4e, 0x40, 0xa3, 0x95, 0x47, 0x12, 0x9c, 0xc2, 0x59,
	0x84, 0x3e, 0x85, 0xb6, 0xc3, 0x3a, 0xc8, 0x43, 0xb8, 0xa6, 0xb7, 0x8c, 0x9c, 0xec, 0x5d, 0x06,
	0x65, 0x0f, 0x40, 0xb2, 0xc0, 0x1d, 0x8a, 0xf2, 0xea, 0x43, 0x51, 0x93, 0xcc, 0x35, 0xad, 0x5d,
	0x58, 0x57, 0xdb, 0x99, 0x09, 0x9d, 0xff, 0x86, 0x6f, 0x29, 0xf4, 0x53, 0x68, 0x90, 0x9b, 0x94,
	0x72, 0x12, 0x05, 0xaa, 0xe5, 0xe9, 0x4c, 0xd7, 0x8f, 0xbb, 0x3d, 0xd3, 0x0f, 0x7b, 0xae, 0x1f,
	0xf6, 0x86, 0xae, 0x1f, 0xfa, 0x75, 0xab, 0xaf, 0x38, 0xe8, 0x14, 0xda, 0x8c, 0x4f, 0x70, 0x42,
	0xbf, 0xd2, 0xc7, 0x62, 0x11, 0xd0, 0xfa, 0xea, 0x80, 0x76, 0xf2, 0xca, 0x2e, 0xb4, 0x17, 0xb0,
	0x69, 0xa0, 0x20, 0xbc, 0xb3, 0xb1, 0x7a, 0xdd, 0x42, 0x01, 0x7d, 0x0c, 0x4d, 0xc9, 0x82, 0x11,
	0x09, 0x38, 0x89, 0x09, 0x16, 0x24, 0xea, 0x6c, 0xea, 0xb4, 0x34, 0x24, 0x3b, 0x25, 0xbe, 0xe5,
	0x79, 0x6f, 0x61, 0xfb, 0x97, 0x38, 0xa6, 0x91, 0xf6, 0xe3, 0x13, 0x31, 0x8f, 0x25, 0xea, 0xc0,
	0x86, 0x98, 0x87, 0xa1, 0xeb, 0x21, 0x9b, 0xbe, 0x23, 0x95, 0x64, 0x46, 0x84, 0xc0, 0x13, 0x07,
	0xb8, 0x23, 0xbd, 0x3f, 0xad, 0xc1, 0xae, 0x01, 0xbd, 0x8f, 0xe3, 0x98, 0x26, 0x93, 0xe1, 0x94,
	0x13, 0x31, 0x65, 0x71, 0x84, 0x7e, 0x03, 0xdb, 0xa6, 0x12, 0x03, 0x95, 0x87, 0x99, 0x6e, 0x65,
	0xa6, 0xba, 0x8e, 0x8b, 0x75, 0x7d, 0x77, 0x65, 0xef, 0x52, 0x2f, 0x1b, 0xb2, 0x13, 0xbd, 0xe8,
	0x4d, 0x22, 0xf9, 0xad, 0xdf, 0x14, 0x05, 0x26, 0x3a, 0x87, 0xb6, 0x74, 0x0b, 0x82, 0x70, 0x4a,
	0xc2, 0xab, 0x40, 0xde, 0xa6, 0x26, 0xbe, 0xe6, 0x71, 0xd7, 0x79, 0x58, 0x18, 0xed, 0x2b, 0x95,
	0xe1, 0x6d, 0x4a, 0x7c, 0x24, 0x97, 0x78, 0xdd, 0x13, 0xd8, 0x59, 0xe1, 0x14, 0x6d, 0x43, 0xf9,
	0x8a, 0xdc, 0xda, 0x73, 0xa5, 0x7e, 0xb3, 0xcb, 0xcb, 0x1c, 0x28, 0x43, 0xfc, 0x78, 0xed, 0xf3,
	0x92, 0xf7, 0x8f, 0x12, 0x74, 0x2e, 0x69, 0x44, 0xfa, 0x53, 0x4c, 0x93, 0xb3, 0xe8, 0x24, 0x89,
	0xbe, 0x20, 0x74, 0x32, 0x95, 0xaf, 0x69, 0x28, 0xd1, 0x97, 0xd0, 0xa4, 0x51, 0x30, 0xd5, 0x8c,
	0x20, 0xa2, 0xe1, 0x12, 0x12, 0xf7, 0xad, 0xec, 0x9d, 0xe5, 0x08, 0x83, 0x44, 0x83, 0xe6, 0x58,
	0xdd, 0x9f, 0x41, 0x6b, 0x49, 0x25, 0x1f, 0x77, 0x75, 0x45, 0xdc, 0xe5, 0x7c, 0xdc, 0x7f, 0x2c,
	0xc1, 0x61, 0xe6, 0x3d, 0x89, 0xc8, 0x0d, 0x4d, 0x26, 0xaa, 0x27, 0xf0, 0x99, 0x2e, 0x8e, 0x73,
	0x2a, 0x24, 0xfa, 0x2d, 0xec, 0x53, 0x2b, 0x0a, 0x68, 0x26, 0x0b, 0x62, 0x2a, 0xdc, 0x56, 0x3e,
	0x5e, 0xde, 0xca, 0xb2, 0x31, 0x7f, 0x8f, 0xae, 0xf6, 0xe0, 0x7d, 0x5d, 0x82, 0x27, 0x0f, 0xad,
	0x44, 0xfb, 0xb0, 0x19, 0x2a, 0x99, 0xeb, 0x16, 0x55, 0x7f, 0x23, 0x34, 0x80, 0xa1, 0x4f, 0xa0,
	0xa9, 0xcd, 0x12, 0x07, 0xb1, 0xdd, 0xe5, 0x23, 0xcb, 0x35, 0xf0, 0xa0, 0x97, 0xb0, 0x63, 0x4e,
	0x86, 0x53, 0xce, 0xae, 0xd7, 0xb2, 0xbf, 0xad, 0x8e, 0xc7, 0x99, 0x11, 0x98, 0x5b, 0xf6, 0xdf,
	0x25, 0xd8, 0xe9, 0x73, 0x26, 0x84, 0x0e, 0xe9, 0x34, 0x66, 0xe1, 0xd5, 0x6b, 0x2c, 0x31, 0x7a,
	0x07, 0x1f, 0x08, 0x1a, 0x91, 0xc0, 0x44, 0x33, 0x52, 0xfc, 0x20, 0xc2, 0x12, 0x5b, 0x1c, 0xba,
	0x4b, 0x38, 0x2c, 0x96, 0xfa, 0x48, 0x2c, 0xf1, 0xd0, 0x25, 0xec, 0xa5, 0x98, 0x93, 0x44, 0x2e,
	0x1b, 0x34, 0xb7, 0xc0, 0x13, 0x67, 0x70, 0xa0, 0xd5, 0xee, 0x98, 0x6c, 0xa7, 0x2b, 0xb8, 0xe8,
	0x18, 0x3e, 0x48, 0x39, 0xb9, 0xa6, 0x6c, 0x2e, 0xac, 0x41, 0x0b, 0x8c, 0xd9, 0xec, 0x8e, 0x13,
	0xea, 0x15, 0x06, 0x1e, 0xef, 0x5f, 0x25, 0x40, 0xcb, 0x31, 0xab, 0xbe, 0x68, 0xd7, 0x96, 0xf4,
	0x5a, 0x4b, 0xa1, 0xcf, 0xa1, 0xe5, 0x2c, 0xe3, 0x88, 0x70, 0x73, 0x75, 0xae, 0x1a, 0x69, 0xb6,
	0x46, 0xc6, 0x89, 0xd2, 0xd2, 0x37, 0xe8, 0xaf, 0xe1, 0x99, 0xe4, 0x38, 0x11, 0x38, 0xd4, 0x35,
	0x24, 0x24, 0x96, 0x73, 0x11, 0xd8, 0x79, 0x4f, 0x72, 0x42, 0x02, 0x3d, 0x1e, 0xad, 0x9a, 0x01,
	0x0e, 0x72, 0x0b, 0x2f, 0xf5, 0xba, 0x6c, 0xf6, 0xf2, 0xd5, 0xe4, 0x94, 0xaf, 0x92, 0x4a, 0xa1,
	0x4a, 0xbc, 0x7f, 0x56, 0xa0, 0xbd, 0x0a, 0xc2, 0x7b, 0x77, 0x38, 0x80, 0xdd, 0x50, 0xe5, 0xdf,
	0x26, 0x86, 0xdc, 0x48, 0x8e, 0x5d, 0x62, 0x54, 0x68, 0x8f, 0x5d, 0x68, 0x59, 0x95, 0xbc, 0x51,
	0x3a, 0x3a, 0x2f, 0x3b, 0xe1, 0x32, 0xb3, 0x10, 0x5d, 0xb9, 0x58, 0xc3, 0xdf, 0x10, 0x94, 0xca,
	0xb7, 0x01, 0x25, 0x84, 0x1d, 0x57, 0xf2, 0xb9, 0xa9, 0xba, 0x53, 0xd5, 0xe5, 0xf5, 0xd9, 0x43,
	0xe5, 0xd5, 0xb3, 0x27, 0x22, 0x1b, 0xa4, 0x4d, 0x0f, 0x6a, 0xd1, 0xbb, 0x7c, 0xf4, 0x0b, 0x80,
	0x1c, 0x42, 0xeb, 0xda, 0xf6, 0x8b, 0x07, 0x6d, 0x2f, 0x70, 0x31, 0x36, 0x6b, 0xc4, 0xd1, 0xdd,
	0x2f, 0x61, 0x77, 0xb5, 0xe3, 0x7c, 0x67, 0x2b, 0x9b, 0xce, 0x76, 0x94, 0xef, 0x6c, 0xf5, 0x63,
	0xb4, 0xfc, 0x3c, 0xc8, 0x75, 0xbb, 0xee, 0x4f, 0xa0, 0x59, 0x74, 0xfb, 0xbf, 0x7a, 0x7c, 0x23,
	0xdf, 0x2b, 0x7f, 0x9f, 0xef, 0x08, 0x59, 0x5a, 0xbf, 0x61, 0xee, 0x4a, 0xdf, 0x22, 0x77, 0xde,
	0xef, 0x60, 0xdf, 0x42, 0xb1, 0xe2, 0x6c, 0xfe, 0x7f, 0x5b, 0x91, 0xf7, 0xf7, 0x12, 0x3c, 0xc9,
	0xf6, 0x67, 0x01, 0xe4, 0x8c, 0x8d, 0xd5, 0x38, 0x4b, 0x6e, 0x24, 0xfa, 0x11, 0xec, 0x8f, 0xd8,
	0x3c, 0x89, 0x82, 0x42, 0xc7, 0x2a, 0x1c, 0x9e, 0x5d, 0xad, 0x90, 0xcb, 0xb7, 0x6d, 0xbe, 0x43,
	0x78, 0x9a, 0x7f, 0xd1, 0x8d, 0x39, 0x9b, 0x15, 0xac, 0x3c, 0x90, 0xbe, 0xfd, 0xec, 0x65, 0xf7,
	0x96, 0xb3, 0x59, 0xce, 0xb6, 0xf7, 0x97, 0x32, 0xec, 0xd9, 0x1b, 0x83, 0x4a, 0x8a, 0x63, 0x3b,
	0x38, 0x2d, 0x1d, 0xb6, 0x3b, 0x17, 0xc6, 0x73, 0xd8, 0x08, 0x39, 0xc1, 0x92, 0x71, 0xeb, 0x76,
	0xf9, 0xb5, 0x64, 0xe5, 0xe8, 0x0c, 0x90, 0xfe, 0x55, 0x89, 0x5d, 0x3c, 0x79, 0x6d, 0x6f, 0x7a,
	0x68, 0x08, 0x6c, 0xb9, 0x55, 0x0b, 0x16, 0x7a, 0x01, 0x2d, 0x73, 0x42, 0x72, 0x37, 0x68, 0xa7,
	0x72, 0x58, 0x3e, 0x6a, 0xf8, 0xdb, 0x5a, 0x90, 0xbf, 0xee, 0x5e, 0xc3, 0xc1, 0xc2, 0xaf, 0x9d,
	0x1b, 0xcc, 0xc0, 0x9d, 0x21, 0x56, 0xd5, 0x80, 0x3f, 0x76, 0x6a, 0x06, 0xe8, 0xf7, 0x49, 0x0e,
	0x1f, 0x74, 0x06, 0x1f, 0x19, 0x0c, 0xec, 0x76, 0x82, 0x94, 0xd3, 0x6b, 0x1a, 0x93, 0x09, 0x09,
	0x52, 0x4e, 0x04, 0xe1, 0xd7, 0x24, 0xd2, 0xa3, 0xe8, 0xa6, 0xff, 0xa1, 0x56, 0xec, 0x1b, 0xbd,
	0x81, 0x53, 0x1b, 0x38, 0x2d, 0xf4, 0x43, 0xd8, 0xcb, 0xd5, 0x9a, 0x64, 0x57, 0x24, 0x09, 0xec,
	0xbb, 0x63, 0x43, 0x9f, 0x9d, 0xf6, 0xa2, 0xa2, 0x86, 0x4a, 0x68, 0xe6, 0x29, 0xef, 0x3f, 0x25,
	0xa8, 0x0f, 0xb3, 0x1a, 0x47, 0xcf, 0xa0, 0xa2, 0x72, 0x7f, 0xdf, 0x2b, 0x55, 0x0b, 0xd1, 0x01,
	0xac, 0x49, 0x76, 0x5f, 0x6a, 0xd6, 0x24, 0x43, 0xdf, 0x85, 0x26, 0x27, 0x63, 0x5d, 0xb9, 0xe6,
	0x75, 0x67, 0x2f, 0xb6, 0x3b, 0xdc, 0xbc, 0xde, 0x80, 0x93, 0x31, 0xbd, 0xb1, 0xc3, 0xfd, 0x1d,
	0x2e, 0xfa, 0x10, 0x72, 0xaf, 0x30, 0x0d, 0x6c, 0xf1, 0x5d, 0x96, 0x3d, 0x0e, 0xd6, 0x0b, 0x8f,
	0x83, 0xa7, 0x50, 0x13, 0x74, 0x92, 0x60, 0x39, 0xe7, 0xa4, 0xf3, 0xe7, 0x0b, 0x2d, 0xcb, 0x38,
	0xdf, 0xff, 0x14, 0xd0, 0xf2, 0x00, 0x8a, 0xea, 0xb0, 0x71, 0x7a, 0x72, 0x7e, 0x72, 0xd1, 0x7f,
	0xb3, 0xfd, 0x1d, 0xf4, 0x08, 0x6a, 0x27, 0xe7, 0xe7, 0xef, 0x7f, 0xa5, 0xc9, 0xd2, 0x69, 0xfb,
	0x6f, 0x6b, 0xad, 0x93, 0x37, 0xf1, 0xb8, 0xd7, 0xb7, 0x8d, 0x53, 0x57, 0xd6, 0xba, 0x2e, 0xb0,
	0xcf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xf6, 0xed, 0xde, 0xb6, 0x11, 0x00, 0x00,
}
